name: Tests and coverage

on:
  push:
    branches:
      - '**'

jobs:
  upload-coverage-data:
    runs-on: ubuntu-latest
    env:
      PYTHON: '3.8'
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8

      - name: Generate coverage report
        run: |
          pip3 install coverage
          pip3 install -r requirements.txt
          cd tests/
          sudo mkdir /var/log/workout-plan-server
          sudo chmod 777 /var/log/workout-plan-server
          PYTHONPATH=../ coverage run --branch --source=../ --omit=./* -m unittest discover -s .
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: tests/coverage.xml
          flags: unit-integ-tests
          name: upload-coverage-data
